#!/bin/bash

# Script to convert a single raw *.nvd files a *.txt file for each satellite
# This uses the parsesin program to convert *.nvd files to *.txt files
# To call:
#    $ ./parsesin_allsvn inputfile.nvd OUTPUTDIR/

# get input file and output directory from arguments
basedir=$(dirname "$0")
infile="$1"
outdir="$2"

parsesin="/parsesin"

# define output file parameters
file2="_"
outfiletype=".txt"

filename=$(basename "${infile%.*}")
for ((  i = 1 ;  i <= 32;  i++  ))
do
    printf -v k "%02d" $i
    outfile=$outdir$filename$file2$k$outfiletype
    $basedir$parsesin $i $infile $outfile
done

